TheAlgorithms/R

- README.md
re-organised README.md file as requested in #1
> Organising README.md

- clustering/kmeans_raw_R.R
I would to contribute my R code to this repo and this script is me using raw R to achieve kmeans algorithm
> achieve kmeans algorithm using raw R code

- regression/Logistic Regression.R
Hi,
I have added an example showing how to implement the simple logistic regression algorithm in R.
> Added the simple logistic regression algorithm in R

- regression/Multiple Linear Regression.R
Hi,
I have added an example of implementation of the multiple linear regression algorithm in R
> Added multiple linear regression algorithm in R

- datamanipulation/OneHotEncode.R
Corrected Typo from "Code" to "Encode".
> Renamed OneHotEncode.R

- sorting/Bubble sort.R
- created a new directory to hold sorting algorithms in R, starting off with the bubble sort. 
- will add more sorting algorithms if this PR is merged (or if sorting algorithms are accepted)
> Add bubble sort algorithm

- README.md
- sorting/Merge sort.R
Proper naming convention is followed.
> Add merge sort algorithm

- README.md
- sorting/Quick sort.R
- sorting/Radix sort.R
Plus added a short note on `c("radix", "quick")` regarding R's `sort` function
> Add radix sort algorithm 

- clustering/gmm.R
gaussian mixture models using mclust
> New algorithm for clustering

- README.md
The old links did not match the file names.
> Fixed broken links to sorting algorithms

- Data-Manipulation/OneHotEncode.R
- Mathematics/Factorial.R
- Mathematics/Prime.R
- Regression-Algorithms/linearRegressionRawR.R
Currently in the process of writing improvements to pre-existing code to (a) improve it's performance in some way or (b) bring it in line with idiomatic R.
Factorial.R was rewritten to be more idiomatic in R; linearRegressionRawR.R now uses singular value decomposition; Prime.R now is optimized in the divisors it uses to check a number against (it should be around 6 times faster or more for odd numbers on average).
> Improving existing code.

- DIRECTORY.md
- Mathematics/HammingDistance.R
- README.md
I implemented the algorithm to calculate the hamming distance between two strings.
> Hamming distance R

- Sorting-Algorithms/counting_sort.R
Implementated the counting sort algorithm in R. I tried to keep the format of the others sorting algorithms, but if format changes are required, just let me know :)
> Create counting.sort function

- DIRECTORY.md
- mathematics/bisection_method.r
The bisection method is a root-finding method that applies to any continuous function for which one knows two values with opposite signs.
> Add Bisection Method

- DIRECTORY.md
- documentation/josephus_problem.html
- documentation/josephus_problem.md
- mathematics/josephus_problem.r
> Add josephus problem

- DIRECTORY.md
- documentation/amicable_numbers.html
- documentation/amicable_numbers.md
- mathematics/amicable_numbers.r
Add amicable number checker implementation in R
> feat: add amicable number checker

- .gitpod.Dockerfile
- .gitpod.yml
- README.md
> Add Gitpod setup

- text_manipulation/rearrangeWays.R
This algorithm calculates the number of possible ways in which a string can be rearranged.
> An algorithm for determining the number of possible rearrangements of a string

- text_manipulation/is.uppercase.R
This algorithm checks if a string is in uppercase. It returns a boolean value based on the outcome of the check.
> An algorithm for checking if a string is in uppercase

- data_manipulation/shorten.vector.R
An algorithm for reducing the length of a vector.
> Added shorten.vector.R
